# ===============================
# SERVER CONFIG
# ===============================
server.port=8080
server.servlet.context-path=/revconnect


# ===============================
# DATABASE CONFIG (MySQL)
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/RevConnectP2
spring.datasource.username=root
spring.datasource.password=Vishal@123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# ===============================
# JPA / HIBERNATE CONFIG
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


# ===============================
# CONNECTION POOL (Hikari - default)
# ===============================
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5


# ===============================
# LOGGING
# ===============================
logging.level.org.springframework=INFO
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE


# ===============================
# JACKSON (JSON)
# ===============================
spring.jackson.serialization.FAIL_ON_EMPTY_BEANS=false
spring.jackson.time-zone=Asia/Kolkata

jwt.secret=revconnect-secret-key-very-secure
jwt.expiration=86400000